# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='sht_incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IM', models.CharField(blank=True, max_length=7, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('sht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Incident_Handover', to='dashboard.sht')),
            ],
        ),
        migrations.CreateModel(
            name='sht_monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IM', models.CharField(blank=True, max_length=7, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('sht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Monitoring_Handover', to='dashboard.sht')),
            ],
        ),
        migrations.CreateModel(
            name='sht_other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('oth_sht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Other_Handover', to='dashboard.sht')),
            ],
        ),
        migrations.CreateModel(
            name='sht_tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TM', models.CharField(blank=True, max_length=7, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('sht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task_Handover', to='dashboard.sht')),
            ],
        ),
    ]
