# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sht',
            options={'ordering': ['date'], 'verbose_name': 'ShiftHandover', 'verbose_name_plural': 'ShiftHandovers'},
        ),
        migrations.AlterModelOptions(
            name='sht_incidents',
            options={'ordering': ['IM'], 'verbose_name': 'Incident', 'verbose_name_plural': 'Incident Handover'},
        ),
        migrations.AlterModelOptions(
            name='sht_monitoring',
            options={'ordering': ['IM'], 'verbose_name': 'Monitoring', 'verbose_name_plural': 'Monitoring Handover'},
        ),
        migrations.AlterModelOptions(
            name='sht_other',
            options={'ordering': ['name'], 'verbose_name': 'Other', 'verbose_name_plural': 'Other Information'},
        ),
        migrations.AlterModelOptions(
            name='sht_tasks',
            options={'ordering': ['CM'], 'verbose_name': 'Task', 'verbose_name_plural': 'Change Handover'},
        ),
        migrations.RenameField(
            model_name='sht_other',
            old_name='oth_sht',
            new_name='sht',
        ),
        migrations.AddField(
            model_name='sht_incidents',
            name='application',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sht_incidents',
            name='costumer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sht_monitoring',
            name='application',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sht_monitoring',
            name='costumer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sht_tasks',
            name='CM',
            field=models.CharField(default=django.utils.timezone.now, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sht_tasks',
            name='application',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sht_tasks',
            name='costumer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sht_tasks',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sht_tasks',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sht',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sht_incidents',
            name='IM',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='sht_incidents',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sht_monitoring',
            name='IM',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='sht_monitoring',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sht_other',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sht_other',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sht_tasks',
            name='TM',
            field=models.CharField(max_length=7),
        ),
    ]
