# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170529_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='sht',
            name='pd',
            field=models.CharField(choices=[('NS', 'Night Shift'), ('MS', 'Morning Shift')], default='MS', max_length=2),
        ),
    ]
