# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sht_pd'),
    ]

    operations = [
        migrations.CreateModel(
            name='oncall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'oncall',
                'verbose_name_plural': 'oncalls',
            },
        ),
        migrations.AlterField(
            model_name='sht',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sht',
            name='pd',
            field=models.CharField(choices=[('NS', 'Night Shift'), ('MS', 'Morning Shift')], default='MS', max_length=2, verbose_name='Part of the day'),
        ),
    ]
